# Generated by Django 5.2.3 on 2025-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_brand_fr', models.CharField(max_length=120)),
                ('partner_brand_en', models.CharField(max_length=120)),
                ('partner_full_name', models.CharField(max_length=120)),
                ('partnership_page_title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
