# Generated by Django 5.2.3 on 2025-06-26 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_partnership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnership',
            old_name='partner_brand_en',
            new_name='brand_en',
        ),
        migrations.RenameField(
            model_name='partnership',
            old_name='partner_brand_fr',
            new_name='brand_fr',
        ),
        migrations.RenameField(
            model_name='partnership',
            old_name='partner_full_name',
            new_name='owner_full_name',
        ),
        migrations.RenameField(
            model_name='partnership',
            old_name='partnership_page_title',
            new_name='page_title',
        ),
        migrations.AddField(
            model_name='partnership',
            name='page_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
