# Generated by Django 5.2 on 2025-06-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_partner_brand_en_partnership_brand_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='file',
            field=models.FileField(upload_to='partnership_videos'),
        ),
    ]
