# Generated by Django 5.2 on 2025-06-27 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_partnership_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='file',
            field=models.FileField(upload_to='partnership_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])]),
        ),
    ]
